ARC-134,135,136: Grouping Metadata, Add Description, & Populate Date Added
ArchivistProject/archivist-web pull request #14
Opened 2017-03-06 19:38 UTC by y0ungy3

2017-03-11 22:04 UTC, mr2ert commented on src/state/upload/upload-reducers.js
> +            let ID = null;
Why did you have to change this reducer?

2017-03-11 22:37 UTC, y0ungy3 commented on src/state/upload/upload-reducers.js
> +            let ID = null;
it's basically to show the meta data for generic on page load without having to click the checkbox

2017-03-11 22:44 UTC, mr2ert commented on src/state/upload/upload-reducers.js
> +            let ID = null;
Ah, I missed that this was for the upload screen only -- thought it was also potentially affecting the sidebar.

2017-03-11 22:53 UTC, mr2ert requested changes
There are a couple of style things as well that we can worry about next quarter.

2017-03-11 22:53 UTC, mr2ert commented on src/state/upload/upload-reducers.js
> +                    const obj = object;
Why do we need to do this?  Can't we just do `object.checkbox = ...`?

2017-03-11 22:53 UTC, mr2ert commented on src/state/upload/upload-reducers.js
> +                groups: groups.map((object) => {
I'd prefer either `group` or `g` as the name.

2017-03-11 22:53 UTC, mr2ert commented on src/state/upload/upload-reducers.js
> +                    if (object.name === 'Generic') { obj.checkbox = true; } else {
The makes the for-loop above unneeded.  Set `array` equal to a https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set, add the ids here, and use http://stackoverflow.com/a/20070691/2336149 when setting it to `allItemID` below.

2017-03-12 01:06 UTC, y0ungy3 commented on src/state/upload/upload-reducers.js
> +                    const obj = object;
tried that before, eslint doesn't let you...

2017-03-12 01:12 UTC, y0ungy3 commented on src/state/upload/upload-reducers.js
> +                    if (object.name === 'Generic') { obj.checkbox = true; } else {
feel free to make changes

2017-03-12 01:31 UTC, y0ungy3 commented on src/state/upload/upload-reducers.js
> +                groups: groups.map((object) => {
it's named "groups" because that's what the JSON object in the backend is named...so it'll be consistent

2017-03-12 01:31 UTC, mr2ert commented on src/state/upload/upload-reducers.js
> +                groups: groups.map((object) => {
I meant for `object`

2017-03-19 20:34 UTC, mr2ert approved these changes

2017-03-19 21:21 UTC, merged