ARC 141 - Show types for meta data fields in settings
ArchivistProject/archivist-web pull request #15
Opened 2017-03-08 00:31 UTC by y0ungy3

2017-03-10 20:28 UTC, mr2ert requested changes
Can you provide a screenshot?

2017-03-11 18:17 UTC, y0ungy3 commented
![a](https://cloud.githubusercontent.com/assets/16579727/23825723/fad33362-065c-11e7-9094-66a195ab3b18.JPG)
![2](https://cloud.githubusercontent.com/assets/16579727/23825724/fd56e03e-065c-11e7-936d-493a160de1b4.JPG)

2017-03-11 19:52 UTC, mr2ert approved these changes

2017-03-11 19:56 UTC, mr2ert commented
One last thing, can you switch field type and field name here?  After that :shipit: 

<img width="593" alt="screen shot 2017-03-11 at 2 53 13 pm" src="https://cloud.githubusercontent.com/assets/5169821/23826456/9046a386-066a-11e7-8829-5bfdf95ecb0b.png">

2017-03-13 16:31 UTC, merged