ARC-170 Restyle the app
ArchivistProject/archivist-web pull request #26
Opened 2017-04-21 17:24 UTC by y0ungy3

#beautiful

2017-04-21 19:12 UTC, Redwards34 commented
I think it looks pretty good all around here are two small things I found to fix.

- Use cursor: pointer for rows on main file list

- The search tab needs some padding to sides of the text, right now it is a little jumpy when you hover over the options for finding a file.

I also have two other things that are more opinion based changes so let me know what you think.

- Maybe change Archivist words in top left to our logo

- Margin under the nav bar makes thing look a little weird, the sidebar divider ends just before some random whitespace. Not sure exactly what to do but I tried quickly putting something together.

**Current**
![current](https://cloud.githubusercontent.com/assets/20045467/25292534/8a5ecdf4-26a4-11e7-86af-1fea11c8a648.png)

**Option**
![option](https://cloud.githubusercontent.com/assets/20045467/25292539/8f03bf18-26a4-11e7-86ae-7ac1c4d0efa0.png)

If you want that option you would just remove border radius and margin bottom from navbar. Add margin top to the home div.

2017-04-21 21:11 UTC, y0ungy3 commented
yeah I was trying to find where the random white space between the nav bar and the sidebar was at in the code but couldn't find it. You should commit that change Rob, it looks good. 

For the logo on top left, I think it looks kinda weird or out of place since every other items on the nav bar is grey and the logo would just be really colorful. 

Also the <hr/> divider in the settings screen, do you think it looks kinda weird? I was thinking of either putting everything into one big grey box (that's how it is right now) or separate each section into their own grey box and get rid of the divider.

2017-04-22 18:59 UTC, Redwards34 commented
The dividers do look a little out of place but not too terrible. It doesn't look that bad without them entirely either.

That idea for the logo sounds good as well if you think you can make it fit the styling.

2017-04-25 20:42 UTC, tjboswell commented
Looks good, there are some changes that need to be made though:

**action bar**

- The action bar is rounded, which looks off to me. At least the top corners should not be rounded
- The search icon should be to the right of search bar on the action bar
- Also, I like the idea of having the colored icon for the home link on the action bar, let me know if you want to do it/need me to make the icons

**main screen**

- The hover color for elements should be the primary (purple) color. For example, the page change arrows, sidebar toggle hover, and sidebar tab hover are all gray
- The no results message has a border around it which should be hidden. (do a search for some random tags)

**advanced search**

- The search 'cards' have weird looking inputs. Right now the dropdowns are the same color as the background which makes it hard to read.
- Hovering over a row's x changes the background instead of the icon. The buttons also aren’t aligned with the row
- Dropdowns for metadata should fit on same line, not 2
- Tags filter and/or dropdown is not aligned properly

**upload screen**

- I think that upload button should be below data entry. Seems weird if you have to scroll back up to upload a new item.
- Font/spacing seems off in general and the page takes up a lot of vertical space. I think you can reduce the spacing, font sizes, header padding, etc to make it a little more compact

**settings screen**

- The button to delete an item type is currently below metadata fields, I think it would make more sense as an X or “delete” next to each item type in the top list
- Change password shouldn’t be a button, should just display inputs on page load
- The logo isn't square and looks stretched out

2017-04-25 20:42 UTC, tjboswell requested changes

2017-04-25 20:42 UTC, tjboswell commented on src/views/sidebar/components/sidebar.scss
>      overflow: scroll;
can get rid of this, not needed

2017-04-25 20:42 UTC, tjboswell commented on src/views/sidebar/components/sidebar.scss
add a `width: 100%;` here

2017-05-04 21:13 UTC, mr2ert commented
@y0ungy3 For your last commit, can you please make it a separate PR all on its own?  I know this is odious, but it'll really help with the documentation.

2017-05-04 21:29 UTC, mr2ert commented
@tjboswell 

- "The button to delete an item type is currently below metadata fields, I think it would make more sense as an X or “delete” next to each item type in the top list"
  - IMHO this is fine as it is because this should be a very rare action.  It also aligns with the idea of that list being a selection of "what I want to see/work on".

2017-05-04 21:43 UTC, y0ungy3 commented
@mr2ert you want to keep my last commit in here for now til this PR is in tonight since it's a really small change, then all other bugs can branch off of master from now on or reverse the last commit on this branch...then branch off of master and do my last commit changes on a different branch?

also i made changes to others comments on here that I think should be change, the ones I didn't do cause i dont think theyre necessary and more of personal preferences.

2017-05-04 21:49 UTC, mr2ert commented
@y0ungy3 "reverse the last commit on this branch...then branch off of master and do my last commit changes on a different branch?" This.

Could you indicate what you did/didn't change based on other's comments? (there are so many + so many lines of code/commits it is hard to tell)  Kind of like what I did above for one of Tyler's suggested changes.

2017-05-04 22:34 UTC, y0ungy3 commented
Rob's Comment:

X    Use cursor: pointer for rows on main file list

X    The search tab needs some padding to sides of the text, right now it is a little jumpy when you hover over the options for finding a file.
X    Margin under the nav bar makes thing look a little weird, the sidebar divider ends just before som random whitespace. Not sure exactly what to do but I tried quickly putting something together.

Tyler's Comment:
action bar

X    The action bar is rounded, which looks off to me. At least the top corners should not be rounded
X   The search icon should be to the right of search bar on the action bar
    Also, I like the idea of having the colored icon for the home link on the action bar, let me know if you want to do it/need me to make the icons

main screen

    The hover color for elements should be the primary (purple) color. For example, the page change arrows, sidebar toggle hover, and sidebar tab hover are all gray
 X   The no results message has a border around it which should be hidden. (do a search for some random tags)

advanced search

    The search 'cards' have weird looking inputs. Right now the dropdowns are the same color as the background which makes it hard to read.
X    Hovering over a row's x changes the background instead of the icon. The buttons also aren’t aligned with the row
X    Dropdowns for metadata should fit on same line, not 2
X    Tags filter and/or dropdown is not aligned properly

upload screen

X    I think that upload button should be below data entry. Seems weird if you have to scroll back up to upload a new item.
X    Font/spacing seems off in general and the page takes up a lot of vertical space. I think you can reduce the spacing, font sizes, header padding, etc to make it a little more compact

settings screen

    The button to delete an item type is currently below metadata fields, I think it would make more sense as an X or “delete” next to each item type in the top list
    Change password shouldn’t be a button, should just display inputs on page load
X    The logo isn't square and looks stretched out


x means been changed

2017-05-04 22:44 UTC, tjboswell commented
First, we're still using bootstrap; I thought we had agreed to get rid of it. It's not worth removing it now because it would take too much time, but it's causing a lot of inconsistencies in our styles. For example:

- We have purple buttons on the sidebar and upload screen. However in the settings page, we have buttons with gray/white gradients.
- The checkboxes on the upload screen are styled differently and have an animation while the ones in the search sidebar tab are plain.
- The fonts for text inputs on the search tab/upload screen/settings screen are different and the text is larger. 
- (not just bootstrap, but related): We are aligning buttons different in different components. For example, the metadata tab left-aligns buttons but the search tab centers them. 

Those are the main issues that I see with it.

There are still a few issues that I think need to be fixed (doesn't have to be this PR).

- I still think the upload screen is way too large and spread out. Font-sizes, margins, and padding can be substantially reduced. I also think the right side can be expanded to be wider. Right now it seems very cramped. The upload icon does not need to take up 40% of the width
- There are some alignment issues. I know we created a ticket for the action bar, but there are also issues with the search filters like this: 
<img width="297" alt="screen shot 2017-05-04 at 6 26 09 pm" src="https://cloud.githubusercontent.com/assets/6114497/25727482/7dc748ca-30f7-11e7-882e-0589f82fbc1d.png">
- There are some color issues for active/hovered elements. These include the arrows to navigate pages, the tabs in the sidebar, and the edited metadata titles (especially on the darker gray which makes it unreadable)
<img width="295" alt="screen shot 2017-05-04 at 6 33 12 pm" src="https://cloud.githubusercontent.com/assets/6114497/25727617/31fe88c6-30f8-11e7-833d-354c9e19b291.png">

2017-05-05 01:19 UTC, y0ungy3 commented
@tjboswell all the changes to your previous comment should be there now. Take a look.

Only the action bar and the list for categories in the settings that I use bootstrap for cause it's a lot easier & faster to do. Otherwise, everything else are not bootstrap.

2017-05-05 19:27 UTC, tjboswell commented
looks good to me now. there are still some issues but those will be handled by other tickets.

2017-05-05 19:28 UTC, mr2ert commented
@tjboswell Can you accept the changes at the bottom of the PR?

2017-05-05 19:29 UTC, tjboswell approved these changes

2017-05-05 19:58 UTC, merged